### ISSUE TITLE
server.py error message

### ISSUE THREAD

**Issue by tristanlee** [shadowsocksrr/shadowsocksr#15]
My OS is Ubuntu 16.04 LTS, I met error msg when I run server.py, it seem like I need a mysql server to support shadowsocksR? plz help me.

root@localhost:~/shadowsocksr# ./server.py
IPv6 support
2017-10-13 09:10:19 INFO     util.py:85 loading libcrypto from libcrypto.so.1.0.0
2017-10-13 09:10:19 INFO     asyncdns.py:324 dns server: [('139.162.73.5', 53), ('139.162.74.5', 53), ('139.162.75.5', 53), ('139.162.66.5', 53), ('139.162.67.5', 53), ('139.162.68.5', 53), ('139.162.69.5', 53), ('139.162.70.5', 53), ('139.162.71.5', 53), ('139.162.72.5', 53)]
2017-10-13 09:10:19 INFO     shell.py:72 ShadowsocksR 3.4.0 2017-07-27
2017-10-13 09:10:19 INFO     db_transfer.py:238 current process RLIMIT_NOFILE resource: soft 1024 hard 65536
2017-10-13 09:10:19 ERROR    db_transfer.py:266 Traceback (most recent call last):
  File "/root/shadowsocksr/db_transfer.py", line 248, in thread_db
    rows = db_instance.pull_db_all_user()
  File "/root/shadowsocksr/db_transfer.py", line 383, in pull_db_all_user
    db=self.cfg["db"], charset='utf8')
  File "/usr/local/lib/python2.7/dist-packages/cymysql/__init__.py", line 85, in Connect
    return Connection(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/cymysql/connections.py", line 245, in __init__
    self._connect()
  File "/usr/local/lib/python2.7/dist-packages/cymysql/connections.py", line 410, in _connect
    raise OperationalError(2003, "Can't connect to MySQL server on %r (%s)" % (self.host, e.args[0]))
OperationalError: (2003, "Can't connect to MySQL server on u'127.0.0.1' (111)")

**Comment by leukios** [comment]
Do you run  shadowsocksr for personal use or sharing with others? For the former, you should run shadowsocksr/shadowsocks/server.py.
