### ISSUE TITLE
'NoneType' object has no attribute 'dispose'

### ISSUE THREAD

**Issue by ankino17** [shadowsocksrr/shadowsocksr#35]
2017-12-18 07:23:14 ERROR    server_pool.py:87 'NoneType' object has no attribute 'dispose'
Traceback (most recent call last):
  File "/root/shadowsocksrr/server_pool.py", line 81, in _loop
    loop.run()
  File "/root/shadowsocksrr/shadowsocks/eventloop.py", line 221, in run
    handle = handler.handle_event(sock, fd, event) or handle
  File "/root/shadowsocksrr/shadowsocks/tcprelay.py", line 1443, in handle_event
    handle = handler.handle_event(sock, fd, event)
  File "/root/shadowsocksrr/shadowsocks/tcprelay.py", line 1062, in handle_event
    self._on_remote_read(sock == self._remote_sock)
  File "/root/shadowsocksrr/shadowsocks/tcprelay.py", line 960, in _on_remote_read
    self.destroy()
  File "/root/shadowsocksrr/shadowsocks/tcprelay.py", line 1166, in destroy
    self._encryptor.dispose()
AttributeError: 'NoneType' object has no attribute 'dispose'
2017-12-18 07:23:20 INFO     server_pool.py:186 stopped server at 0.0.0.0:443
2017-12-18 07:23:20 INFO     server_pool.py:186 stopped server at 0.0.0.0:995

995端口 android客户端
客户端配置aes-128-ctr origin plain 无DNS转发 china dns:119.29.29.29:53 dns:8.8.8.8:53 自定义ACL
服务器配置 aes-128-ctr auth_sha1_v4_compatible tls1.2_ticket_auth_compatible
ssrr版本3.2.1

**Comment by ankino17** [comment]
好像看到了类似的问题 #12 
CentOS Linux release 7.4.1708 (Core) 
Python 2.7

2017-12-18 07:23:20 INFO     server_pool.py:186 stopped server at 0.0.0.0:443
2017-12-18 07:23:20 INFO     server_pool.py:186 stopped server at 0.0.0.0:995
IPv6 not support
[root@ankino shadowsocksrr]#

**Comment by AkaneAkaza** [comment]
更新代码试试
