### ISSUE TITLE
ERROR    db_transfer.py:266 Traceback …… InternalError: (1043, u'Bad handshake')

### ISSUE THREAD

**Issue by ghost** [shadowsocksrr/shadowsocksr#56]
/shadowsocksr# python server.py
IPv6 support
2018-05-02 14:51:07 INFO     util.py:92 loading libcrypto from libcrypto.so.1.0.0
2018-05-02 14:51:07 INFO     asyncdns.py:287 black_hostname_list init as : []
2018-05-02 14:51:07 INFO     asyncdns.py:335 dns server: [('8.8.8.8', 53), ('8.8.4.4', 53)]
2018-05-02 14:51:07 INFO     shell.py:74 ShadowsocksR 3.4.0 2017-07-27
2018-05-02 14:51:07 INFO     db_transfer.py:238 current process RLIMIT_NOFILE resource: soft 65536 hard 65536
2018-05-02 14:51:08 ERROR    db_transfer.py:266 Traceback (most recent call last):
  File "/root/shadowsocksr/db_transfer.py", line 248, in thread_db
    rows = db_instance.pull_db_all_user()
  File "/root/shadowsocksr/db_transfer.py", line 383, in pull_db_all_user
    db=self.cfg["db"], charset='utf8')
  File "/root/shadowsocksr/cymysql/__init__.py", line 81, in Connect
    return Connection(*args, **kwargs)
  File "/root/shadowsocksr/cymysql/connections.py", line 222, in __init__
    self._connect()
  File "/root/shadowsocksr/cymysql/connections.py", line 388, in _connect
    self._request_authentication()
  File "/root/shadowsocksr/cymysql/connections.py", line 460, in _request_authentication
    auth_packet = MysqlPacket(self)
  File "/root/shadowsocksr/cymysql/packet.py", line 67, in __init__
    raise_mysql_exception(self.__data)
  File "/root/shadowsocksr/cymysql/err.py", line 142, in raise_mysql_exception
    _check_mysql_exception(errinfo)
  File "/root/shadowsocksr/cymysql/err.py", line 138, in _check_mysql_exception
    raise InternalError(errno, errorvalue)
InternalError: (1043, u'Bad handshake')

老机器没这个问题，添加的新机器一直这个错误

**Comment by sahrechiiz** [comment]
same

**Comment by sahrechiiz** [comment]
是CyMySQL的问题 回到之前的版本就好

rm -rf CyMySQL
rm -rf cymysql
git clone https://github.com/nakagami/CyMySQL.git
cd CyMySQL
git checkout 0cfc3e62302ee1c94369914631bb0ae77a652a4b
cd ..
mv CyMySQL/cymysql ./
rm -rf CyMySQL

**Comment by ghost** [comment]
Problem Solved ,thank you ! @sahrechiiz
