### ISSUE TITLE
Akkariiin/Experimental's version error

### ISSUE THREAD

**Issue by yefeiyu** [shadowsocksrr/shadowsocksr#75]
Cannot start after installation, there is an error
Which I installed is 'Akkariiin/Experimental' version.
@Akkariiin please help me.
```

origin@debian-x86:~$ ssr start
[sudo] password for origin: 
Traceback (most recent call last):
  File "local.py", line 31, in <module>
    from shadowsocks import shell, daemon, eventloop, tcprelay, udprelay, asyncdns
  File "/home/origin/.local/share/shadowsocksr/shadowsocks/../shadowsocks/shell.py", line 137
    def get_config(is_local) -> typing.Dict[str, any]:
                             ^
SyntaxError: invalid syntax

```

**Comment by Akkariiin** [comment]
NO, this brunch NOT for use, now.

PLEASE DON'T USE IT.


if you what try new feature, use Akkariiin/dev instend.
