### ISSUE TITLE
数据库连接正常退出调试提示UDP端口关闭

### ISSUE THREAD

**Issue by q847633684** [shadowsocksrr/shadowsocksr#80]
```
[root@us shadowsocks]# python server.py
loaded collections.OrderedDict
IPv6 support
INFO: ShadowsocksR 3.4.0 mod by esdeathlove
INFO: current process RLIMIT_NOFILE resource: soft 1024 hard 4096
INFO: loading config from user-config.json
2019-03-07 06:28:56 INFO     util.py:49 loading libcrypto from libcrypto.so.10
2019-03-07 06:28:56 INFO     asyncdns.py:324 dns server: [('8.8.8.8', 53), ('8.8.4.4', 53)]
2019-03-07 06:28:56 INFO     asyncdns.py:324 dns server: [('8.8.8.8', 53), ('8.8.4.4', 53)]
2019-03-07 06:28:57 INFO     auto_block.py:89 Read hosts.deny from line 13
2019-03-07 06:28:57 INFO     db_transfer.py:822 db start server at port [60489] pass [pouhst] protocol [auth_chain_a] method [rc4-md5] obfs [plain]
2019-03-07 06:28:57 INFO     server_pool.py:146 starting server at [::]:60489
2019-03-07 06:28:57 INFO     server_pool.py:176 starting server at 0.0.0.0:60489
2019-03-07 06:28:57 INFO     db_transfer.py:822 db start server at port [52162] pass [Haven79] protocol [origin] method [rc4-md5] obfs [plain]
2019-03-07 06:28:57 INFO     server_pool.py:146 starting server at [::]:52162
2019-03-07 06:28:57 INFO     server_pool.py:176 starting server at 0.0.0.0:52162
2019-03-07 06:28:57 INFO     db_transfer.py:822 db start server at port [37093] pass [EopfuC] protocol [origin] method [rc4-md5] obfs [plain]
2019-03-07 06:28:57 INFO     server_pool.py:146 starting server at [::]:37093
2019-03-07 06:28:57 INFO     server_pool.py:176 starting server at 0.0.0.0:37093
2019-03-07 06:28:57 INFO     db_transfer.py:822 db start server at port [22767] pass [htqd] protocol [auth_sha1_v4_compatible] method [rc4-md5] obfs [plain]
2019-03-07 06:28:57 INFO     server_pool.py:146 starting server at [::]:22767
2019-03-07 06:28:57 INFO     server_pool.py:176 starting server at 0.0.0.0:22767
2019-03-07 06:28:57 INFO     db_transfer.py:822 db start server at port [27667] pass [vWbaPl] protocol [origin] method [rc4-md5] obfs [plain]
2019-03-07 06:28:57 INFO     server_pool.py:146 starting server at [::]:27667
2019-03-07 06:28:57 INFO     server_pool.py:176 starting server at 0.0.0.0:27667
2019-03-07 06:28:57 INFO     db_transfer.py:822 db start server at port [39983] pass [uznMnF] protocol [origin] method [rc4-md5] obfs [plain]
2019-03-07 06:28:57 INFO     server_pool.py:146 starting server at [::]:39983
2019-03-07 06:28:57 INFO     server_pool.py:176 starting server at 0.0.0.0:39983
2019-03-07 06:28:57 INFO     db_transfer.py:822 db start server at port [54555] pass [EOqWwG] protocol [origin] method [rc4-md5] obfs [plain]
2019-03-07 06:28:57 INFO     server_pool.py:146 starting server at [::]:54555
2019-03-07 06:28:57 INFO     server_pool.py:176 starting server at 0.0.0.0:54555
^CTraceback (most recent call last):
  File "server.py", line 78, in main
    threadMain.join(10.0)
  File "/usr/lib64/python2.7/threading.py", line 962, in join
    self.__block.wait(delay, balancing)
  File "/usr/lib64/python2.7/threading.py", line 362, in wait
    _sleep(delay)
KeyboardInterrupt
2019-03-07 06:29:00 INFO     server_pool.py:225 stopped server at 0.0.0.0:52162 already stop
2019-03-07 06:29:00 INFO     server_pool.py:249 stopped server at [::]:52162
2019-03-07 06:29:00 INFO     server_pool.py:225 stopped server at 0.0.0.0:27667 already stop
2019-03-07 06:29:00 INFO     server_pool.py:249 stopped server at [::]:27667
2019-03-07 06:29:00 INFO     server_pool.py:225 stopped server at 0.0.0.0:37093 already stop
2019-03-07 06:29:00 INFO     server_pool.py:249 stopped server at [::]:37093
2019-03-07 06:29:00 INFO     server_pool.py:225 stopped server at 0.0.0.0:54555 already stop
2019-03-07 06:29:00 INFO     server_pool.py:249 stopped server at [::]:54555
2019-03-07 06:29:00 INFO     server_pool.py:225 stopped server at 0.0.0.0:60489 already stop
2019-03-07 06:29:00 INFO     server_pool.py:249 stopped server at [::]:60489
2019-03-07 06:29:00 INFO     server_pool.py:225 stopped server at 0.0.0.0:39983 already stop
2019-03-07 06:29:00 INFO     server_pool.py:249 stopped server at [::]:39983
2019-03-07 06:29:00 INFO     server_pool.py:225 stopped server at 0.0.0.0:22767 already stop
2019-03-07 06:29:00 INFO     server_pool.py:249 stopped server at [::]:22767
2019-03-07 06:29:02 INFO     tcprelay.py:2053 closed TCP port 60489
2019-03-07 06:29:02 INFO     udprelay.py:947 closed UDP port 60489
2019-03-07 06:29:02 INFO     udprelay.py:947 closed UDP port 52162
2019-03-07 06:29:02 INFO     udprelay.py:947 closed UDP port 37093
2019-03-07 06:29:02 INFO     udprelay.py:947 closed UDP port 22767
2019-03-07 06:29:02 INFO     udprelay.py:947 closed UDP port 27667
2019-03-07 06:29:02 INFO     udprelay.py:947 closed UDP port 39983
2019-03-07 06:29:02 INFO     udprelay.py:947 closed UDP port 54555
```
> 防火墙关闭过了
> 用的系统是CentOS 7.5+BBR
> Google查找,没有找到相关的解决方法!
>尝试过重建数据库,数据库没有问题
>就剩下系统本身和ss的问题,可是不知道是哪个,找不到解决方法!
>求助各位大佬

**Comment by XingxingLIU123** [comment]
我也遇到了和你一样的问题。vps商家回复禁止搭建，猜测是商家的问题
